### ISSUE TITLE
User can join a game. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/discordpy-connect4-standalone#3]
# Motivation
We want to be able to be able to join a lobby to start the game. Max 2 players. 

# Task implementation
- [x] Implement a command to signal a join/leave
- [x] Implement a command to view the players
- [x] Test the commands out.
