### ISSUE TITLE
Players can complete a game.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/discordpy-connect4-standalone#5]
# Motivation
Now that we can manage join/leaves, we want to be able to actually complete a game. 

# Task implementation
- [x] Remember how to use logic
- [x] When 2 players are in, be able to "start" a game
- [x] Be able to interpret an input for popping and dropping
- [x] Be able to display the board with every input
- [x] Be able to interpret an input for making moves
- [x] Randomize who goes first.
- [x] Be able to create a winning board.
- [x] When you win, signify that the game is over, resetting the variables.
- [x] Create commands to see who's in the game.
- [x] Bind a character to a player.
- [x] Enforce only that player moving on their turn only.
- [x] Create more robust error reporting for helpfulness. 
- [x] Refactor the code so the event handler for messages isn't so long.
