### ISSUE TITLE
Extra mini-features and re-factoring

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/discordpy-connect4-standalone#7]
# Motivation
Now that we can actually complete a game from start to finish, we want to give this game a more complete feeling. We'll do this by implementing a bunch of small features.

# Task implementation
- [x] Create a background task to track if both players are online. If not, remove the player that is offline.
- [x] continue to simplify the code so that it is more de-couplable. 
- [x] refine the user inputs so that it can handle more non-unique inputs.
- [x] Update the readme.
